export const blogPosts = [
  {
    id: 1,
    category: 'Rutas',
    title:
      'Descubre las Rutas Secretas del Ávila: Guía para Aficionados al Senderismo',
    date: '20 de Enero, 2025',
    image: '/images/rutas.jpg',
    link: '/blog/rutas-secretas',
  },
  {
    id: 2,
    category: 'Testimonios',
    title: 'Historias de Aventura: Experiencias Inolvidables en el Ávila',
    date: '1 de Febrero, 2025',
    image: '/images/testimonios.jpg',
    link: '/blog/historias-aventura',
  },
  {
    id: 3,
    category: 'Equipo',
    title: 'El Equipo Esencial para Tus Aventuras en la Naturaleza',
    date: '31 de Enero, 2025',
    image: '/images/equipo.jpg',
    link: '/blog/equipo-esencial',
  },
  {
    id: 4,
    category: 'Consejos',
    title: 'Tips para Conservar el Medio Ambiente Durante Tus Excursiones',
    date: '15 de Enero, 2025',
    image: '/images/consejos.jpg',
    link: '/blog/conservar-medio-ambiente',
  },
  {
    id: 5,
    category: 'Conservación',
    title: 'Impacto Ambiental y Conservación: Cuidando Nuestro Parque Nacional',
    date: '3 de Febrero, 2025',
    image: '/images/conservacion.jpg',
    link: '/blog/impacto-ambiental',
  },
  {
    id: 6,
    category: 'Preparación',
    title: 'Cómo Prepararte Físicamente para una Excursión en el Ávila',
    date: '23 de Enero, 2025',
    image: '/images/preparacion.jpg',
    link: '/blog/preparacion-excursion',
  },
];
