import React from 'react';
import { useLocation } from 'react-router-dom';
import './Blog.css';
import BackButton from '../../components/BackButton/BackButton.jsx';

function BlogContent() {
  const location = useLocation();
  const { title, category, image, createdAt } = location.state || {};

  if (!location.state) return <></>;

  return (
    <div className='ContenidoBlog'>
      <BackButton where='/blog' />
      <p className='categoria'>{category}</p>
      <h2 className='titulo'>{title}</h2>
      <div className='datos parrafos'>
        <p>{createdAt}</p>
      </div>
      <img src={image} alt={title} className='imagen-contenido' />
      <p className='parrafos'>
        {' '}
        {/* Here will be the content of the blog generated by QuillJS */}
        Explorar el Parque Nacional El Ávila es una experiencia única para los
        amantes de la naturaleza y la aventura. Sin embargo, la seguridad debe
        ser siempre una prioridad. En este artículo, te ofrecemos 5 consejos
        esenciales para disfrutar de una excursión segura, sin sacrificar la
        emoción de descubrir nuevos paisajes y rutas.
      </p>

      <div>
        <h2 className='titulo'>
          Consejo 1: Planifica tu Ruta y Conoce el Terreno
        </h2>
        <p className='parrafos'>
          Antes de salir, investiga las rutas disponibles y elige aquella que se
          adapte a tu nivel de experiencia. Consulta mapas, revisa pronósticos
          meteorológicos y pregunta a expertos o a otros excursionistas sobre
          las condiciones actuales del sendero.
        </p>
      </div>

      <p className='comentario'>
        “ Traveling can expose you to new environments and potential health
        risks, so it&apos;s crucial to take precautions to stay safe and
        healthy. ”
      </p>
    </div>
  );
}

export default BlogContent;
